site_name: bouzomgi
nav:
  - About: about.md
  - Tech:
      - Password Security: tech/password-security.md
      - JWTs: tech/jwt.md
  - Money:
      - Double Entry Bookkeeping: money/double-entry-bookkeeping.md
markdown_extensions:
  - footnotes
extra_css:
  - style.css
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  highlightjs: true
