site_name: bouzomgi
nav:
  - Home: index.md
  - About: about.md
  - Money:
      - Double Entry Bookkeeping: double-entry-bookkeeping.md
markdown_extensions:
  - footnotes
extra_css:
  - style.css
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  highlightjs: true
